[libraries]
commons-csv = { module = "org.apache.commons:commons-csv", version = "1.14.1" }
commons-io = { module = "commons-io:commons-io", version = "2.21.0"}
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
lwjgl = { module = "org.lwjgl:lwjgl", version = "3.3.6" }

# [bundles]
# lwjgl-bundle = ["lwjgl", "lwjgl-glfw", "lwjgl-opengl", "lwjgl-stb"]

[plugins]
dep-resolve = { id = "org.gradlex.jvm-dependency-conflict-resolution", version = "2.5"}
